// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: google/rpc/errdetails/error_details.proto

package errdetails

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RetryInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RetryInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RetryInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RetryInfoMultiError, or nil
// if none found.
func (m *RetryInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *RetryInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRetryDelay()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RetryInfoValidationError{
					field:  "RetryDelay",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RetryInfoValidationError{
					field:  "RetryDelay",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRetryDelay()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RetryInfoValidationError{
				field:  "RetryDelay",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RetryInfoMultiError(errors)
	}

	return nil
}

// RetryInfoMultiError is an error wrapping multiple validation errors returned
// by RetryInfo.ValidateAll() if the designated constraints aren't met.
type RetryInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RetryInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RetryInfoMultiError) AllErrors() []error { return m }

// RetryInfoValidationError is the validation error returned by
// RetryInfo.Validate if the designated constraints aren't met.
type RetryInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetryInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetryInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetryInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetryInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetryInfoValidationError) ErrorName() string { return "RetryInfoValidationError" }

// Error satisfies the builtin error interface
func (e RetryInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetryInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetryInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetryInfoValidationError{}

// Validate checks the field values on DebugInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DebugInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DebugInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DebugInfoMultiError, or nil
// if none found.
func (m *DebugInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *DebugInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Detail

	if len(errors) > 0 {
		return DebugInfoMultiError(errors)
	}

	return nil
}

// DebugInfoMultiError is an error wrapping multiple validation errors returned
// by DebugInfo.ValidateAll() if the designated constraints aren't met.
type DebugInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DebugInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DebugInfoMultiError) AllErrors() []error { return m }

// DebugInfoValidationError is the validation error returned by
// DebugInfo.Validate if the designated constraints aren't met.
type DebugInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DebugInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DebugInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DebugInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DebugInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DebugInfoValidationError) ErrorName() string { return "DebugInfoValidationError" }

// Error satisfies the builtin error interface
func (e DebugInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDebugInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DebugInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DebugInfoValidationError{}

// Validate checks the field values on QuotaFailure with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QuotaFailure) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QuotaFailure with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QuotaFailureMultiError, or
// nil if none found.
func (m *QuotaFailure) ValidateAll() error {
	return m.validate(true)
}

func (m *QuotaFailure) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetViolations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QuotaFailureValidationError{
						field:  fmt.Sprintf("Violations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QuotaFailureValidationError{
						field:  fmt.Sprintf("Violations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QuotaFailureValidationError{
					field:  fmt.Sprintf("Violations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return QuotaFailureMultiError(errors)
	}

	return nil
}

// QuotaFailureMultiError is an error wrapping multiple validation errors
// returned by QuotaFailure.ValidateAll() if the designated constraints aren't met.
type QuotaFailureMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QuotaFailureMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QuotaFailureMultiError) AllErrors() []error { return m }

// QuotaFailureValidationError is the validation error returned by
// QuotaFailure.Validate if the designated constraints aren't met.
type QuotaFailureValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QuotaFailureValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QuotaFailureValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QuotaFailureValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QuotaFailureValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QuotaFailureValidationError) ErrorName() string { return "QuotaFailureValidationError" }

// Error satisfies the builtin error interface
func (e QuotaFailureValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuotaFailure.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QuotaFailureValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QuotaFailureValidationError{}

// Validate checks the field values on ErrorInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ErrorInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ErrorInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ErrorInfoMultiError, or nil
// if none found.
func (m *ErrorInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *ErrorInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Reason

	// no validation rules for Domain

	// no validation rules for Metadata

	if len(errors) > 0 {
		return ErrorInfoMultiError(errors)
	}

	return nil
}

// ErrorInfoMultiError is an error wrapping multiple validation errors returned
// by ErrorInfo.ValidateAll() if the designated constraints aren't met.
type ErrorInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ErrorInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ErrorInfoMultiError) AllErrors() []error { return m }

// ErrorInfoValidationError is the validation error returned by
// ErrorInfo.Validate if the designated constraints aren't met.
type ErrorInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ErrorInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ErrorInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ErrorInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ErrorInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ErrorInfoValidationError) ErrorName() string { return "ErrorInfoValidationError" }

// Error satisfies the builtin error interface
func (e ErrorInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sErrorInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ErrorInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ErrorInfoValidationError{}

// Validate checks the field values on PreconditionFailure with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PreconditionFailure) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PreconditionFailure with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PreconditionFailureMultiError, or nil if none found.
func (m *PreconditionFailure) ValidateAll() error {
	return m.validate(true)
}

func (m *PreconditionFailure) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetViolations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PreconditionFailureValidationError{
						field:  fmt.Sprintf("Violations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PreconditionFailureValidationError{
						field:  fmt.Sprintf("Violations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PreconditionFailureValidationError{
					field:  fmt.Sprintf("Violations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PreconditionFailureMultiError(errors)
	}

	return nil
}

// PreconditionFailureMultiError is an error wrapping multiple validation
// errors returned by PreconditionFailure.ValidateAll() if the designated
// constraints aren't met.
type PreconditionFailureMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PreconditionFailureMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PreconditionFailureMultiError) AllErrors() []error { return m }

// PreconditionFailureValidationError is the validation error returned by
// PreconditionFailure.Validate if the designated constraints aren't met.
type PreconditionFailureValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreconditionFailureValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreconditionFailureValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreconditionFailureValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreconditionFailureValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreconditionFailureValidationError) ErrorName() string {
	return "PreconditionFailureValidationError"
}

// Error satisfies the builtin error interface
func (e PreconditionFailureValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreconditionFailure.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreconditionFailureValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreconditionFailureValidationError{}

// Validate checks the field values on BadRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BadRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BadRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BadRequestMultiError, or
// nil if none found.
func (m *BadRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BadRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetFieldViolations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BadRequestValidationError{
						field:  fmt.Sprintf("FieldViolations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BadRequestValidationError{
						field:  fmt.Sprintf("FieldViolations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BadRequestValidationError{
					field:  fmt.Sprintf("FieldViolations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BadRequestMultiError(errors)
	}

	return nil
}

// BadRequestMultiError is an error wrapping multiple validation errors
// returned by BadRequest.ValidateAll() if the designated constraints aren't met.
type BadRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BadRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BadRequestMultiError) AllErrors() []error { return m }

// BadRequestValidationError is the validation error returned by
// BadRequest.Validate if the designated constraints aren't met.
type BadRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BadRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BadRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BadRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BadRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BadRequestValidationError) ErrorName() string { return "BadRequestValidationError" }

// Error satisfies the builtin error interface
func (e BadRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBadRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BadRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BadRequestValidationError{}

// Validate checks the field values on RequestInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RequestInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RequestInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RequestInfoMultiError, or
// nil if none found.
func (m *RequestInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *RequestInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RequestId

	// no validation rules for ServingData

	if len(errors) > 0 {
		return RequestInfoMultiError(errors)
	}

	return nil
}

// RequestInfoMultiError is an error wrapping multiple validation errors
// returned by RequestInfo.ValidateAll() if the designated constraints aren't met.
type RequestInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RequestInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RequestInfoMultiError) AllErrors() []error { return m }

// RequestInfoValidationError is the validation error returned by
// RequestInfo.Validate if the designated constraints aren't met.
type RequestInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RequestInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RequestInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RequestInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RequestInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RequestInfoValidationError) ErrorName() string { return "RequestInfoValidationError" }

// Error satisfies the builtin error interface
func (e RequestInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRequestInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RequestInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RequestInfoValidationError{}

// Validate checks the field values on ResourceInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ResourceInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ResourceInfoMultiError, or
// nil if none found.
func (m *ResourceInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ResourceType

	// no validation rules for ResourceName

	// no validation rules for Owner

	// no validation rules for Description

	if len(errors) > 0 {
		return ResourceInfoMultiError(errors)
	}

	return nil
}

// ResourceInfoMultiError is an error wrapping multiple validation errors
// returned by ResourceInfo.ValidateAll() if the designated constraints aren't met.
type ResourceInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceInfoMultiError) AllErrors() []error { return m }

// ResourceInfoValidationError is the validation error returned by
// ResourceInfo.Validate if the designated constraints aren't met.
type ResourceInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceInfoValidationError) ErrorName() string { return "ResourceInfoValidationError" }

// Error satisfies the builtin error interface
func (e ResourceInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceInfoValidationError{}

// Validate checks the field values on Help with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Help) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Help with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in HelpMultiError, or nil if none found.
func (m *Help) ValidateAll() error {
	return m.validate(true)
}

func (m *Help) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetLinks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HelpValidationError{
						field:  fmt.Sprintf("Links[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HelpValidationError{
						field:  fmt.Sprintf("Links[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HelpValidationError{
					field:  fmt.Sprintf("Links[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HelpMultiError(errors)
	}

	return nil
}

// HelpMultiError is an error wrapping multiple validation errors returned by
// Help.ValidateAll() if the designated constraints aren't met.
type HelpMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HelpMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HelpMultiError) AllErrors() []error { return m }

// HelpValidationError is the validation error returned by Help.Validate if the
// designated constraints aren't met.
type HelpValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HelpValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HelpValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HelpValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HelpValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HelpValidationError) ErrorName() string { return "HelpValidationError" }

// Error satisfies the builtin error interface
func (e HelpValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHelp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HelpValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HelpValidationError{}

// Validate checks the field values on LocalizedMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LocalizedMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LocalizedMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LocalizedMessageMultiError, or nil if none found.
func (m *LocalizedMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *LocalizedMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Locale

	// no validation rules for Message

	if len(errors) > 0 {
		return LocalizedMessageMultiError(errors)
	}

	return nil
}

// LocalizedMessageMultiError is an error wrapping multiple validation errors
// returned by LocalizedMessage.ValidateAll() if the designated constraints
// aren't met.
type LocalizedMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LocalizedMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LocalizedMessageMultiError) AllErrors() []error { return m }

// LocalizedMessageValidationError is the validation error returned by
// LocalizedMessage.Validate if the designated constraints aren't met.
type LocalizedMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LocalizedMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LocalizedMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LocalizedMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LocalizedMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LocalizedMessageValidationError) ErrorName() string { return "LocalizedMessageValidationError" }

// Error satisfies the builtin error interface
func (e LocalizedMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLocalizedMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LocalizedMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LocalizedMessageValidationError{}

// Validate checks the field values on QuotaFailure_Violation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QuotaFailure_Violation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QuotaFailure_Violation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QuotaFailure_ViolationMultiError, or nil if none found.
func (m *QuotaFailure_Violation) ValidateAll() error {
	return m.validate(true)
}

func (m *QuotaFailure_Violation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Subject

	// no validation rules for Description

	if len(errors) > 0 {
		return QuotaFailure_ViolationMultiError(errors)
	}

	return nil
}

// QuotaFailure_ViolationMultiError is an error wrapping multiple validation
// errors returned by QuotaFailure_Violation.ValidateAll() if the designated
// constraints aren't met.
type QuotaFailure_ViolationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QuotaFailure_ViolationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QuotaFailure_ViolationMultiError) AllErrors() []error { return m }

// QuotaFailure_ViolationValidationError is the validation error returned by
// QuotaFailure_Violation.Validate if the designated constraints aren't met.
type QuotaFailure_ViolationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QuotaFailure_ViolationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QuotaFailure_ViolationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QuotaFailure_ViolationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QuotaFailure_ViolationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QuotaFailure_ViolationValidationError) ErrorName() string {
	return "QuotaFailure_ViolationValidationError"
}

// Error satisfies the builtin error interface
func (e QuotaFailure_ViolationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuotaFailure_Violation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QuotaFailure_ViolationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QuotaFailure_ViolationValidationError{}

// Validate checks the field values on PreconditionFailure_Violation with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PreconditionFailure_Violation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PreconditionFailure_Violation with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// PreconditionFailure_ViolationMultiError, or nil if none found.
func (m *PreconditionFailure_Violation) ValidateAll() error {
	return m.validate(true)
}

func (m *PreconditionFailure_Violation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Subject

	// no validation rules for Description

	if len(errors) > 0 {
		return PreconditionFailure_ViolationMultiError(errors)
	}

	return nil
}

// PreconditionFailure_ViolationMultiError is an error wrapping multiple
// validation errors returned by PreconditionFailure_Violation.ValidateAll()
// if the designated constraints aren't met.
type PreconditionFailure_ViolationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PreconditionFailure_ViolationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PreconditionFailure_ViolationMultiError) AllErrors() []error { return m }

// PreconditionFailure_ViolationValidationError is the validation error
// returned by PreconditionFailure_Violation.Validate if the designated
// constraints aren't met.
type PreconditionFailure_ViolationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreconditionFailure_ViolationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreconditionFailure_ViolationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreconditionFailure_ViolationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreconditionFailure_ViolationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreconditionFailure_ViolationValidationError) ErrorName() string {
	return "PreconditionFailure_ViolationValidationError"
}

// Error satisfies the builtin error interface
func (e PreconditionFailure_ViolationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreconditionFailure_Violation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreconditionFailure_ViolationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreconditionFailure_ViolationValidationError{}

// Validate checks the field values on BadRequest_FieldViolation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BadRequest_FieldViolation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BadRequest_FieldViolation with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BadRequest_FieldViolationMultiError, or nil if none found.
func (m *BadRequest_FieldViolation) ValidateAll() error {
	return m.validate(true)
}

func (m *BadRequest_FieldViolation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Field

	// no validation rules for Description

	if len(errors) > 0 {
		return BadRequest_FieldViolationMultiError(errors)
	}

	return nil
}

// BadRequest_FieldViolationMultiError is an error wrapping multiple validation
// errors returned by BadRequest_FieldViolation.ValidateAll() if the
// designated constraints aren't met.
type BadRequest_FieldViolationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BadRequest_FieldViolationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BadRequest_FieldViolationMultiError) AllErrors() []error { return m }

// BadRequest_FieldViolationValidationError is the validation error returned by
// BadRequest_FieldViolation.Validate if the designated constraints aren't met.
type BadRequest_FieldViolationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BadRequest_FieldViolationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BadRequest_FieldViolationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BadRequest_FieldViolationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BadRequest_FieldViolationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BadRequest_FieldViolationValidationError) ErrorName() string {
	return "BadRequest_FieldViolationValidationError"
}

// Error satisfies the builtin error interface
func (e BadRequest_FieldViolationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBadRequest_FieldViolation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BadRequest_FieldViolationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BadRequest_FieldViolationValidationError{}

// Validate checks the field values on Help_Link with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Help_Link) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Help_Link with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Help_LinkMultiError, or nil
// if none found.
func (m *Help_Link) ValidateAll() error {
	return m.validate(true)
}

func (m *Help_Link) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Description

	// no validation rules for Url

	if len(errors) > 0 {
		return Help_LinkMultiError(errors)
	}

	return nil
}

// Help_LinkMultiError is an error wrapping multiple validation errors returned
// by Help_Link.ValidateAll() if the designated constraints aren't met.
type Help_LinkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Help_LinkMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Help_LinkMultiError) AllErrors() []error { return m }

// Help_LinkValidationError is the validation error returned by
// Help_Link.Validate if the designated constraints aren't met.
type Help_LinkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Help_LinkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Help_LinkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Help_LinkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Help_LinkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Help_LinkValidationError) ErrorName() string { return "Help_LinkValidationError" }

// Error satisfies the builtin error interface
func (e Help_LinkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHelp_Link.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Help_LinkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Help_LinkValidationError{}
